from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RECON = ROOT / "Pipeline" / "Reconciliation"
PROMPTS = RECON / "prompts"

MARKER = "2026-08-21 FRESH RUN CLOSURE"

PROMPT_BLOCKS = {
    PROMPTS / "reconcile.md": r'''

## 2026-08-21 FRESH RUN CLOSURE

### Reconciliation provenance boundary

- `CLAUDE.md` may be automatically loaded by Claude Code as **operating instructions**, but it is NOT an approved reconciliation evidence source and it is NOT game-design canon. Never cite `CLAUDE.md` as the authority for a GDD requirement, ownership rule, dependency, exclusive-resource lock, acceptance criterion, validation requirement, summary conclusion, or unresolved design question.
- The approved sources remain the current GDD plus the explicitly allowed current-project/historical evidence paths in this prompt. If an operating instruction helped you reason about where to inspect, re-source the resulting claim to the actual GDD/repository evidence before emitting it.
- Do not turn routing metadata, reconciliation/verification prompts, prior repair prose, verifier output, patch scripts, or candidate bookkeeping into project requirements or evidence.

### Current gameplay-navigation writer locks

For the current repository architecture, `gameplay-navigation-locomotion` is expected to integrate the NavMesh/walkability representation into the canonical scene objects generated by `Assets/NoSafeCircle/DoorPrototype/Editor/DoorPrototypeSceneBuilder.cs`. The current builder clears and recreates `Floor`, `Walls`, and `DoorRoot`, and saves `Assets/NoSafeCircle/DoorPrototype/Scenes/DoorPrototype.unity`.

Therefore, while that architecture remains current, preserve all three navigation locks:

- `logical:gameplay-walkability-surface`
- `repo-file:Assets/NoSafeCircle/DoorPrototype/Editor/DoorPrototypeSceneBuilder.cs`
- `unity-scene:Assets/NoSafeCircle/DoorPrototype/Scenes/DoorPrototype.unity`

The builder/scene pair is a derived current-write-surface decision grounded in the GDD's `Current prototype scene-builder lock` plus the actual builder's destructive root rebuild/save behavior. Do not cite `CLAUDE.md` for it and do not invent a dependency on `world-visual-foundation` merely because both tasks share those locks. If a later approved/current architecture moves navigation authoring to a separately owned asset that the builder does not regenerate, reconciliation should follow that new real write surface instead.

### Scene-builder rule is a durable process constraint

The GDD's `Shared Context and Coordination Rules — Current prototype scene-builder lock` is itself a required development-process invariant. The `global_pipeline` domain must preserve it in `non_code_requirements` as a typed `pipeline_constraint` (for example title `Current prototype scene-builder exclusive-write lock`). Per-task `exclusive_resources` are applications of this rule; they do not replace the durable process record.

### Seed-assessment consistency

`seed_assessment.status` is summary metadata, not a new GDD requirement. It must agree with its detail lists: blockers imply `blocked`; warnings/unresolved review state imply `ready_with_warnings`; otherwise use `ready`. Do not invent a GDD requirement from candidate self-assessment metadata.
''',
    PROMPTS / "verification" / "coverage_auditor.md": r'''

## 2026-08-21 FRESH RUN CLOSURE

### Requirement-map source boundary

The `requirements` array is a map of **actual current-GDD requirements only**. Every row must originate in the GDD and its `reference` must identify the relevant GDD section/passage.

Candidate bookkeeping or verifier observations are NOT GDD requirements. In particular, never create requirement-map rows for `seed_assessment`, candidate/refiner metadata, verification status, routing metadata, run IDs, warning counts, or other pipeline bookkeeping. If such metadata is internally inconsistent, report an ordinary finding in the appropriate category; do not put it in `requirements` and do not cause deterministic GDD-coverage enforcement to treat it as canon.

The GDD `Shared Context and Coordination Rules — Current prototype scene-builder lock` is `required_process` and should map to a typed `pipeline_constraint` in `non_code_requirements`. Per-task builder/scene locks do not substitute for that durable process record.
''',
    PROMPTS / "verification" / "structure_auditor.md": r'''

## 2026-08-21 FRESH RUN CLOSURE

For the current scene-built prototype architecture, verify `gameplay-navigation-locomotion` against the real writer surface. `DoorPrototypeSceneBuilder.cs` clears/recreates the current `Floor`, `Walls`, and `DoorRoot` and saves the canonical `DoorPrototype.unity` scene. A navigation implementation that adds/configures the NavMesh/walkability representation through those maintained objects therefore shares the builder+scene exclusive-write pair with other current scene-authoring work, in addition to `logical:gameplay-walkability-surface`. This is a lock/concurrency relationship, not a dependency on `world-visual-foundation`. Re-evaluate the locks if the current approved repository architecture later moves navigation authoring to a separately owned asset.
''',
    PROMPTS / "verification" / "refiner.md": r'''

## 2026-08-21 FRESH RUN CLOSURE

- `CLAUDE.md` is operating context only and is never admissible reconciliation/GDD evidence. Remove or re-source every `CLAUDE.md` attribution in summaries, evidence, dependencies, locks, acceptance/validation text, and unresolved questions. Use the real GDD/repository support or clearly labeled derived rationale.
- When the current builder architecture still owns the canonical scene's walkable roots, ensure `gameplay-navigation-locomotion` carries `logical:gameplay-walkability-surface`, the `DoorPrototypeSceneBuilder.cs` repo-file lock, and the canonical `DoorPrototype.unity` scene lock. Do not convert that write collision into a dependency on `world-visual-foundation`.
- Ensure the GDD's `Current prototype scene-builder lock` exists as a typed `pipeline_constraint` in `non_code_requirements`; task-level exclusive-resource entries do not replace that process invariant.
- Keep `seed_assessment` internally consistent. Candidate self-assessment/bookkeeping is not GDD canon and must never be invented as a coverage requirement.
''',
    PROMPTS / "verification" / "evidence_auditor.md": r'''

## 2026-08-21 FRESH RUN CLOSURE

`CLAUDE.md` is automatically loadable operating context, not an approved reconciliation evidence source. Any candidate string that uses `CLAUDE.md` as authority for a requirement, dependency, ownership decision, lock, summary conclusion, or unresolved design claim is an evidence-provenance defect even if the underlying conclusion can be supported elsewhere. Require the claim to be re-sourced to the real GDD/repository evidence or explicitly labeled as derived rationale.
''',
}


PROVENANCE_AND_SEED_BLOCK = r'''

INTERNAL_PROVENANCE_MARKERS = (
    "claude.md",
    "verified closure",
    "verification-hardening",
    "streaming_verification_refinement_patch/",
    "pipeline/reconciliation/prompts/",
    "pipeline/reconciliation/outputs/",
)


def _collect_internal_provenance_paths(
    value: Any,
    *,
    path: str = "$",
) -> list[str]:
    hits: list[str] = []
    if isinstance(value, dict):
        for key, child in value.items():
            child_path = f"{path}.{key}"
            hits.extend(_collect_internal_provenance_paths(child, path=child_path))
        return hits
    if isinstance(value, list):
        for index, child in enumerate(value):
            hits.extend(
                _collect_internal_provenance_paths(child, path=f"{path}[{index}]")
            )
        return hits
    if isinstance(value, str):
        lowered = value.replace("\\", "/").lower()
        if any(marker in lowered for marker in INTERNAL_PROVENANCE_MARKERS):
            hits.append(path)
    return hits


def validate_reconciliation_provenance(payload: dict[str, Any]) -> None:
    """Reject internal operating/bookkeeping text used as reconciliation evidence."""
    hits = _collect_internal_provenance_paths(payload)
    if not hits:
        return
    preview = ", ".join(hits[:12])
    if len(hits) > 12:
        preview += f", ... (+{len(hits) - 12} more)"
    raise RuntimeError(
        "Reconciliation candidate contains disallowed internal provenance at: "
        + preview
        + ". CLAUDE.md, verifier/patch labels, prompts, and reconciliation outputs "
          "are operating/bookkeeping context, not GDD or repository evidence."
    )


def normalize_seed_assessment_consistency(payload: dict[str, Any]) -> list[str]:
    """Derive seed status from blockers/warnings and explicit unresolved review state."""
    seed = payload.setdefault(
        "seed_assessment",
        {"status": "ready", "blockers": [], "warnings": []},
    )
    blockers = seed.setdefault("blockers", [])
    warnings = seed.setdefault("warnings", [])
    unresolved = payload.get("unresolved_questions", [])

    if not isinstance(blockers, list) or not isinstance(warnings, list):
        raise RuntimeError("seed_assessment blockers/warnings must be lists.")

    if unresolved:
        unresolved_warning = (
            f"{len(unresolved)} unresolved reconciliation question(s) remain for "
            "human/runtime/later-decomposition review."
        )
        if unresolved_warning not in warnings:
            warnings.append(unresolved_warning)

    expected_status = (
        "blocked"
        if blockers
        else "ready_with_warnings"
        if warnings
        else "ready"
    )
    previous = str(seed.get("status", ""))
    if previous == expected_status:
        return []
    seed["status"] = expected_status
    return [f"seed_assessment.status: {previous!r} -> {expected_status!r}"]


def _validate_seed_assessment_consistency(payload: dict[str, Any]) -> None:
    seed = payload.get("seed_assessment", {})
    status = str(seed.get("status", ""))
    blockers = seed.get("blockers", [])
    warnings = seed.get("warnings", [])
    expected = "blocked" if blockers else "ready_with_warnings" if warnings else "ready"
    if status != expected:
        raise RuntimeError(
            "seed_assessment is internally inconsistent: "
            f"status={status!r}, blockers={len(blockers)}, warnings={len(warnings)}; "
            f"expected status {expected!r}."
        )
'''


COVERAGE_BOUNDARY_BLOCK = r'''

INTERNAL_COVERAGE_REQUIREMENT_MARKERS = (
    "seed_assessment",
    "candidate self-assessment",
    "candidate metadata",
    "pipeline/candidate",
    "verification metadata",
    "reconciliation metadata",
    "routing metadata",
)


def _is_internal_candidate_metadata_requirement(requirement: dict[str, Any]) -> bool:
    combined = " ".join(
        str(requirement.get(field, ""))
        for field in ("reference", "requirement", "explanation")
    ).lower()
    return any(marker in combined for marker in INTERNAL_COVERAGE_REQUIREMENT_MARKERS)
'''


def append_prompt_blocks() -> list[str]:
    changed: list[str] = []
    for path, block in PROMPT_BLOCKS.items():
        text = path.read_text(encoding="utf-8")
        if MARKER in text:
            continue
        path.write_text(text.rstrip() + block + "\n", encoding="utf-8")
        changed.append(path.relative_to(ROOT).as_posix())
    return changed


def patch_reconciliation_agent() -> bool:
    path = RECON / "reconciliation_agent.py"
    text = path.read_text(encoding="utf-8")
    changed = False

    if "def validate_reconciliation_provenance(" not in text:
        anchor = (
            "\n# ============================================================\n"
            "# SEMANTIC VALIDATION\n"
            "# ============================================================\n"
        )
        if text.count(anchor) != 1:
            raise RuntimeError("Expected exactly one semantic-validation section anchor.")
        text = text.replace(anchor, PROVENANCE_AND_SEED_BLOCK + anchor, 1)
        changed = True

    old = '''def run_semantic_validation(payload: dict[str, Any]) -> None:\n    ensure_non_code_requirement_type_defaults(payload)\n    ensure_requirement_detail_defaults(payload)\n    ensure_execution_scope_defaults(payload)\n    normalize_execution_scope_consistency(payload)\n    ensure_exclusive_resource_defaults(payload)\n'''
    new = '''def run_semantic_validation(payload: dict[str, Any]) -> None:\n    ensure_non_code_requirement_type_defaults(payload)\n    ensure_requirement_detail_defaults(payload)\n    ensure_execution_scope_defaults(payload)\n    normalize_execution_scope_consistency(payload)\n    normalize_seed_assessment_consistency(payload)\n    ensure_exclusive_resource_defaults(payload)\n    validate_reconciliation_provenance(payload)\n    _validate_seed_assessment_consistency(payload)\n'''
    if old in text:
        text = text.replace(old, new, 1)
        changed = True
    elif new not in text:
        raise RuntimeError("Unable to locate run_semantic_validation prelude.")

    if changed:
        path.write_text(text, encoding="utf-8")
    return changed


def patch_parallel_reconciliation() -> bool:
    path = RECON / "parallel_reconciliation_agent.py"
    text = path.read_text(encoding="utf-8")
    old = '''    seed_status = "ready_with_warnings" if unresolved or merge_warnings else "ready"\n\n    payload = {\n'''
    new = '''    seed_warnings = list(merge_warnings)\n    if unresolved:\n        seed_warnings.append(\n            f"{len(unresolved)} unresolved reconciliation question(s) remain for review."\n        )\n    seed_status = "ready_with_warnings" if seed_warnings else "ready"\n\n    payload = {\n'''
    changed = False
    if old in text:
        text = text.replace(old, new, 1)
        changed = True
    elif new not in text:
        raise RuntimeError("Unable to locate parallel seed-status merge anchor.")

    old_warning = '''            "warnings": merge_warnings,\n'''
    new_warning = '''            "warnings": seed_warnings,\n'''
    if old_warning in text:
        text = text.replace(old_warning, new_warning, 1)
        changed = True
    elif new_warning not in text:
        raise RuntimeError("Unable to locate parallel seed warnings field.")

    if changed:
        path.write_text(text, encoding="utf-8")
    return changed


def patch_verification_crew() -> bool:
    path = RECON / "verification_crew.py"
    text = path.read_text(encoding="utf-8")
    changed = False

    if "def _is_internal_candidate_metadata_requirement(" not in text:
        anchor = "def deterministic_audit_checks(audits: list[dict[str, Any]]) -> list[dict[str, Any]]:\n"
        if text.count(anchor) != 1:
            raise RuntimeError("Expected exactly one deterministic_audit_checks anchor.")
        text = text.replace(anchor, COVERAGE_BOUNDARY_BLOCK + "\n\n" + anchor, 1)
        changed = True

    old_loop = '''        for requirement in requirements:\n            classification = str(requirement.get("classification", ""))\n'''
    new_loop = '''        for requirement in requirements:\n            if _is_internal_candidate_metadata_requirement(requirement):\n                generated.append(\n                    {\n                        "source_agent": "Deterministic Coverage Check",\n                        "source_model": "python",\n                        "finding": {\n                            "finding_id": (\n                                "deterministic-non-gdd-row-"\n                                + deterministic_auditor_slug(agent)\n                                + "-"\n                                + str(requirement.get("requirement_id", "unknown"))\n                            ),\n                            "severity": "warning",\n                            "category": "other",\n                            "title": "Coverage auditor emitted a non-GDD requirement-map row",\n                            "description": (\n                                f"{agent} placed candidate/pipeline metadata in the GDD "\n                                f"requirement map as {requirement.get('requirement_id')}. "\n                                "Candidate bookkeeping may be audited as a finding but is "\n                                "not GDD canon and is excluded from deterministic GDD "\n                                "representation enforcement."\n                            ),\n                            "affected_keys": [\n                                str(value)\n                                for value in requirement.get("mapped_keys", [])\n                                if str(value).strip()\n                            ],\n                            "gdd_evidence": [],\n                            "repository_evidence": [],\n                            "recommended_change": (\n                                "Report candidate/self-assessment consistency as an ordinary "\n                                "finding. Keep the requirements array limited to statements "\n                                "actually sourced from the current GDD."\n                            ),\n                            "requires_human_review": False,\n                        },\n                    }\n                )\n                continue\n\n            classification = str(requirement.get("classification", ""))\n'''
    if old_loop in text:
        text = text.replace(old_loop, new_loop, 1)
        changed = True
    elif new_loop not in text:
        raise RuntimeError("Unable to locate deterministic requirement loop.")

    if changed:
        path.write_text(text, encoding="utf-8")
    return changed


def main() -> int:
    changed_prompts = append_prompt_blocks()
    code_changes = []
    if patch_reconciliation_agent():
        code_changes.append("Pipeline/Reconciliation/reconciliation_agent.py")
    if patch_parallel_reconciliation():
        code_changes.append("Pipeline/Reconciliation/parallel_reconciliation_agent.py")
    if patch_verification_crew():
        code_changes.append("Pipeline/Reconciliation/verification_crew.py")

    if changed_prompts or code_changes:
        print("Installed fresh-run reconciliation/verification closure fixes:")
        for value in changed_prompts + code_changes:
            print(f"  - {value}")
    else:
        print("Fresh-run closure fixes are already installed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
