"""Which ignored artifacts an owned task checkout may carry into admission.

First coverage for this helper. It had none, which is how the allow-list came to
be narrower than its own docstring without anything failing.

The decisive pair is `test_every_artifact_a_unity_run_leaves_behind_is_allowed`
and `test_a_project_file_below_the_root_is_refused`. The first is the real set a
checkout carries after its crew has run Unity -- refusing any of it refuses the
whole class of materialized tasks. The second is the boundary that keeps the
first from becoming "any ignored file anywhere".

THE PYTHON HALF WAS THE SAME OMISSION AND IT COST A DISPATCH. Measured
2026-09-25 across all 51 live task checkouts: five -- NSC-009, NSC-044, NSC-101,
NSC-118, NSC-126 -- were refused for nothing but `Pipeline/*/__pycache__`, and
NSC-118 satisfied every other precondition `reserve` has. So
`BYTECODE_CACHE_ARTIFACTS` below is the same kind of witness as
`UNITY_RUN_ARTIFACTS`: a real captured set, not an invented one.
"""
from __future__ import annotations

import os
import tempfile
import unittest
from pathlib import Path

from Pipeline.AssistantControl.admission import _allowed_ignored_checkout_path


# Captured from NSC-048's checkout, which is clean by ordinary `git status` and
# reports exactly these under `--ignored=matching`. Every one is declared
# generated by the repository's own .gitignore.
UNITY_RUN_ARTIFACTS = (
    "Library/",
    "Logs/",
    "UserSettings/",
    "Assembly-CSharp-firstpass.csproj",
    "NoSafeCircle.DoorPrototype.csproj",
    "NoSafeCircle.DoorPrototype.Editor.csproj",
    "NoSafeCircle.DoorPrototype.Tests.csproj",
    "NoSafeCircle.DoorPrototype.Tests.Editor.csproj",
    "deVoid.Signals.csproj",
    "NSC-048.sln",
    "Pipeline/ExecutionCrew/outputs/",
)

# Captured from NSC-118's checkout 2026-09-25, which `git status` calls clean and
# which reported exactly these seven under `--ignored=matching`. Every one is
# declared generated by the repository's own .gitignore, at line 113.
BYTECODE_CACHE_ARTIFACTS = (
    "Pipeline/AgentRuntime/__pycache__/",
    "Pipeline/AgentRuntime/providers/__pycache__/",
    "Pipeline/ExecutionCrew/__pycache__/",
    "Pipeline/TaskExecution/__pycache__/",
    "Pipeline/TaskGraph/__pycache__/",
    "Pipeline/TaskReviewAgent/__pycache__/",
    "Pipeline/Testing/__pycache__/",
)


class AllowedIgnoredCheckoutPathTests(unittest.TestCase):
    def setUp(self):
        self._temporary = tempfile.TemporaryDirectory(prefix="nsc-ignored-")
        self.checkout = Path(self._temporary.name)

    def tearDown(self):
        self._temporary.cleanup()

    def allowed(self, value: str) -> bool:
        return _allowed_ignored_checkout_path(self.checkout, value)

    def test_every_artifact_a_unity_run_leaves_behind_is_allowed(self):
        """Refusing any of these refuses every task whose crew ran Unity, because
        Unity rewrites them on every open and deleting them does not stick."""
        for artifact in UNITY_RUN_ARTIFACTS:
            with self.subTest(artifact=artifact):
                self.assertTrue(self.allowed(artifact))

    def test_a_project_file_below_the_root_is_refused(self):
        """The boundary that keeps the allowance from becoming "any ignored file".

        Unity generates its project and solution files at the repository root. A
        .csproj deeper in the tree is not Unity's and is a local change.
        """
        for value in ("Assets/Evil.csproj", "Deep/Nested.sln",
                      "Assets/Scenes/Thing.unityproj", "a/b/c.slnx"):
            with self.subTest(value=value):
                self.assertFalse(self.allowed(value))

    def test_an_unrelated_ignored_file_is_still_refused(self):
        for value in ("secrets.txt", "Assets/Scenes/LowerVault.unity",
                      "notes.md", "Build/"):
            with self.subTest(value=value):
                self.assertFalse(self.allowed(value))

    def test_traversal_and_empty_components_are_refused(self):
        for value in ("../escape.csproj", "Library/../../outside", "", "   "):
            with self.subTest(value=value):
                self.assertFalse(self.allowed(value))

    def test_a_traversal_that_lands_back_inside_is_still_refused(self):
        """The case only the component check can refuse.

        The other traversal inputs are caught further down by the resolved-path
        containment test, so they would pass even with the component check
        removed -- a negative test that succeeds on somebody else's guard. This
        one resolves back INSIDE the checkout, so containment accepts it and
        only the explicit ".." rejection stands between it and admission.
        """
        (self.checkout / "Library").mkdir()
        self.assertFalse(self.allowed("Library/../Library"))

    def test_a_redundant_current_directory_component_is_normalised_not_refused(self):
        """Documented rather than asserted from habit: PurePosixPath collapses
        "." before the decision, so these are the allowed paths they name. ".."
        is NOT collapsed, which is why the traversal check above still bites."""
        self.assertTrue(self.allowed("./Library"))
        self.assertTrue(self.allowed("Library/./x"))

    def test_a_suffix_that_merely_contains_a_project_extension_is_refused(self):
        """The match is on the final suffix, not on the name containing one."""
        for value in ("evil.csproj.txt", "sln", "csproj", ".csproj.bak"):
            with self.subTest(value=value):
                self.assertFalse(self.allowed(value))

    def test_the_bare_extension_alone_is_not_a_project_file(self):
        # A dotfile literally named ".sln" is not a Unity solution. Matching on
        # PurePosixPath.suffix rather than a trailing-string test excludes it,
        # because a leading-dot name has no suffix.
        for value in (".sln", ".csproj", ".slnx"):
            with self.subTest(value=value):
                self.assertFalse(self.allowed(value))

    def test_case_differences_do_not_defeat_the_allowance(self):
        # Windows checkouts report whatever case Unity wrote.
        for value in ("MyProject.CSPROJ", "Thing.Sln"):
            with self.subTest(value=value):
                self.assertTrue(self.allowed(value))

    def test_backslashes_are_normalised_before_the_decision(self):
        self.assertTrue(self.allowed("Library\\ScriptAssemblies"))
        self.assertFalse(self.allowed("Assets\\Evil.csproj"))

    def test_a_symlinked_component_is_still_refused(self):
        """Pre-existing protection that must survive the widened allow-list."""
        outside = self.checkout.parent / (self.checkout.name + "-outside")
        outside.mkdir()
        link = self.checkout / "Library"
        try:
            os.symlink(outside, link, target_is_directory=True)
        except (OSError, NotImplementedError, AttributeError) as exc:
            self.skipTest(f"symlink creation unavailable: {exc}")

        try:
            self.assertFalse(
                self.allowed("Library/ScriptAssemblies"),
                "an allowed name must not launder a symlink out of the checkout")
        finally:
            link.unlink()
            outside.rmdir()

    def test_every_bytecode_cache_a_pipeline_import_leaves_behind_is_allowed(self):
        """Refusing any of these refuses every checkout Python has run in.

        This is the NSC-118 case: its checkout satisfied the reconciled
        baseline, the scope pin, the active contract and its dependencies, and
        `reserve` refused it for seven generated bytecode directories. The next
        import recreates them, so deleting them is not a remedy -- the same
        argument the Unity caches above were admitted on.
        """
        for artifact in BYTECODE_CACHE_ARTIFACTS:
            with self.subTest(artifact=artifact):
                self.assertTrue(self.allowed(artifact))

    def test_a_bytecode_cache_is_allowed_at_every_depth_including_the_root(self):
        """Unlike the Unity caches this is NOT root-only, because CPython writes
        it beside whichever package was imported and nobody here chooses that."""
        for value in ("__pycache__", "__pycache__/",
                      "Pipeline/__pycache__/x.cpython-313.pyc",
                      "a/b/c/d/e/__pycache__/deep.cpython-313.pyc"):
            with self.subTest(value=value):
                self.assertTrue(self.allowed(value))

    def test_only_that_exact_directory_name_is_allowed(self):
        """The boundary. Without it the clause becomes "any path mentioning a
        cache", and a `.pyc` written OUTSIDE a `__pycache__` directory is the one
        shape Python will import with no source beside it, so it must stay a
        local change."""
        for value in ("pycache/", "__pycache__x/", "my__pycache__/",
                      "Pipeline/__pycache/x.pyc", "__PYCACHE__/",
                      "Pipeline/TaskGraph/stale.cpython-313.pyc",
                      "Pipeline/__pycach__/x.pyc"):
            with self.subTest(value=value):
                self.assertFalse(self.allowed(value))

    def test_a_symlinked_bytecode_cache_component_is_still_refused(self):
        """The widened clause must not launder a symlink, and it is a SEPARATE
        clause from the Library one above -- so the protection has to be proven
        again on this path rather than inherited from that test."""
        outside = self.checkout.parent / (self.checkout.name + "-pycache-outside")
        outside.mkdir()
        link = self.checkout / "__pycache__"
        try:
            os.symlink(outside, link, target_is_directory=True)
        except (OSError, NotImplementedError, AttributeError) as exc:
            outside.rmdir()
            self.skipTest(f"symlink creation unavailable: {exc}")

        try:
            self.assertFalse(
                self.allowed("__pycache__/planted.cpython-313.pyc"),
                "an allowed name must not launder a symlink out of the checkout")
        finally:
            link.unlink()
            outside.rmdir()

    def test_a_traversal_through_a_bytecode_cache_is_refused(self):
        (self.checkout / "__pycache__").mkdir()
        self.assertFalse(self.allowed("__pycache__/../__pycache__"))


if __name__ == "__main__":
    unittest.main()
